<?php

namespace Extensions\Plugins\Roulette_arckene__208645946\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class RouletteHistory extends Model
{
    use CacheQueryBuilder;

    protected $table = 'roulette__history';

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
