<?php

namespace Extensions\Plugins\Roulette_arckene__208645946\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class RouletteConfig extends Model
{
    use CacheQueryBuilder;

    protected $table = 'roulette__config';
    protected $fillable = ['elements', 'price', 'created_at', 'updated_at'];

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
